### ISSUE TITLE
More examples of Symbol Collisions 

### ISSUE THREAD

**Issue by monkburger** [yugr/ShlibVisibilityChecker#3]
May wish to add this;

https://github.com/heimdal/heimdal/issues/911
https://github.com/DCIT/perl-CryptX/pull/79
https://github.com/DCIT/perl-CryptX/issues/68

(The above was fixed by a specific compiler flag (easiest way without renaming))

Then this:

https://discourse.libsdl.org/t/sdl-init-segfaulting/27826

I think this is an underreported issue, though.

**Comment by yugr** [comment]
Thanks! Do you know if they have been detected with ShlibVisibilityChecker or manually? The `close` bug is particularly good.

**Comment by yugr** [comment]
Added example with crash to README.
